### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by standarddev** [kosukeimai/wru#23]
Me again! 

Code is working great except when I get to the section that uses demo for BLOCK and TRACT

Here is my code

system.time(dblock <- predict_race(dta, census.surname = TRUE, surname.only = FALSE, surname.year = 2010, census.geo = "block",census.key=key,sex=TRUE,age=TRUE))

Here is the error I'm getting now. When I ran the code for county, I did not have the same issue. I do get a similar error when I use BLOCK and TRACT.

Thank you again for taking the time to help me with my issues! 

Robin

Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In merge_surnames(voter.file) :
  Probabilities were imputed for 184 surnames that could not be matched to Census list.
2: In file(con, "r") :
  cannot open URL 'http://api.census.gov/data/2010/sf1?key=9bcb6f80b144a7f05c67fadcc37b0e6a1532ccfd&get=P012D011,P012D012,P012D013,P012D014,P012D015,P012D016,P012D017,P012D018,P012D019,P012D020,P012D021,P012D022,P012D023,P012D024,P012D025,P012D027,P012D028,P012D029,P012D030,P012D031,P012D032,P012D033,P012D034,P012D035,P012D036,P012D037,P012D038,P012D039,P012D040,P012D041,P012D042,P012D043,P012D044,P012D045,P012D046,P012D047,P012D048,P012D049,P012E001,P012E003,P012E004,P012E005,P012E006,P012E007,P012E008,P012E009,P012E010,P012E011,P012E012,P012E013&for=block:*&in=state:17+county:167+tract:003202': HTTP status was '500 Internal Server Error'
[1] "http://api.census.gov/data/2010/sf1?key=9bcb6f80b144a7f05c67fadcc37b0e6a1532ccfd&get=P012D011,P012D012,P012D013,P012D014,P012D015,P012D016,P012D017,P012D018,P012D019,P012D020,P012D021,P012D022,P012D023,P012D024,P012D025,P012D027,P012D028,P012D029,P012D030,P012D031,P012D032,P012D033,P012D034,P012D035,P012D036,P012D037,P012D038,P012D039,P012D040,P012D041,P012D042,P012D043,P012D044,P012D045,P012D046,P012D047,P012D048,P012D049,P012E001,P012E003,P012E004,P012E005,P012E006,P012E007,P012E008,P012E009,P012E010,P012E011,P012E012,P012E013&for=block:*&in=state:17+county:167+tract:003202"
Error in get_census_api_2(data_url, key, x, region) : 
  http://api.census.gov/data/2010/sf1?key=9bcb6f80b144a7f05c67fadcc37b0e6a1532ccfd&get=P012D011,P012D012,P012D013,P012D014,P012D015,P012D016,P012D017,P012D018,P012D019,P012D020,P012D021,P012D022,P012D023,P012D024,P012D025,P012D027,P012D028,P012D029,P012D030,P012D031,P012D032,P012D033,P012D034,P012D035,P012D036,P012D037,P012D038,P012D039,P012D040,P012D041,P012D042,P012D043,P012D044,P012D045,P012D046,P012D047,P012D048,P012D049,P012E001,P012E003,P012E004,P012E005,P012E006,P012E007,P012E008,P012E009,P012E010,P012E011,P012E012,P012E013&for=block:*&in=state:17+county:167+tract:003202
Timing stopped at: 11782.34 2183.92 21368.96

**Comment by HJ08003** [comment]
Hi Robin, 

The error, HTTP status was '500 Internal Server Error', is usually from the web server side, which is the census server. If you click that link, you will see the data in your browser. This means WRU put the correct http request but the census website failed to deliver the data for some reasons. Most likely I would say it was network interruptions. 

Download census data at the block could be time consuming. Besides, there is a high risk of rare and randomly occurred network interruptions. 

One thing you may consider is downloading the census data ahead of time. There are some functions in the WRU let you do that. The function get_census_data() let you download all census data for a list of states, from county level to block level. However, since you are doing so many download request, the chance of running into network interruption at the census server side is still quite high. Here are some alternatives:
1. Do one state at a time (and combine the census objects later).
2. Choose a high level to download. i.e. if you are not using block level information, there is no need to download block level data.

In the README.Md of WRU, we have the last example which shows how to manually construct census objects by using the function census_geo_api(). Please take a look at it.

Also, we are revising get_census_data() so that users can select the level of details (i.e. county, tract, block) to download census data.

It is very unfortunate that census website has network access glitches. The quick solution is re-run your line of code, although the network problem may still occur at random. A better solution will be downloading data at small chuck each but a large number. Thus, re-downloading only the failed one will be less costly. We are working on such a solution.

Hope this helps, Thanks,

-Hubert

**Comment by standarddev** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Yup! I figured this out. I have downloaded the data for each state. Although it still takes a long time, at least I only have to do it once!
Thank you!!
Robin 


Sent from Yahoo Mail for iPhone


On Tuesday, April 4, 2017, 11:58 AM, HJ08003 <notifications@github.com> wrote:


Hi Robin,

The error, HTTP status was '500 Internal Server Error', is usually from the web server side, which is the census server. If you click that link, you will see the data in your browser. This means WRU put the correct http request but the census website failed to deliver the data for some reasons. Most likely I would say it was network interruptions.

Download census data at the block could be time consuming. Besides, there is a high risk of rare and randomly occurred network interruptions.

One thing you may consider is downloading the census data ahead of time. There are some functions in the WRU let you do that. The function get_census_data() let you download all census data for a list of states, from county level to block level. However, since you are doing so many download request, the chance of running into network interruption at the census server side is still quite high. Here are some alternatives:
   
   - Do one state at a time (and combine the census objects later).
   - Choose a high level to download. i.e. if you are not using block level information, there is no need to download block level data.

In the README.Md of WRU, we have the last example which shows how to manually construct census objects by using the function census_geo_api(). Please take a look at it.

Also, we are revising get_census_data() so that users can select the level of details (i.e. county, tract, block) to download census data.

It is very unfortunate that census website has network access glitches. The quick solution is re-run your line of code, although the network problem may still occur at random. A better solution will be downloading data at small chuck each but a large number. Thus, re-downloading only the failed one will be less costly. We are working on such a solution.

Hope this helps, Thanks,

-Hubert
