### ISSUE TITLE
Potential to add territories as additional states?

### ISSUE THREAD

**Issue by justindbk** [kosukeimai/wru#45]
When states in my dataset do not exist in the State.FIPS table that accompanies the package in sysdata.rda, the error message is a little inelegant at the moment:
`Error in tmp[[1]] : subscript out of bounds`

It's trivial for me to remove voters from my dataset that are from the territories (e.g. state %in% c("AS","GU","MP","PR","VI")) but I figured it was worth flagging that the error isn't super informative. And, given that these are real states, it would be helpful to include them in the prediction functions of the package in future!

**Comment by 1beb** [comment]
The US census for 2010 doesn't appear to count many of these. 2020 they started with Guam, but it appears that there is no state fips in the census API. 

https://api.census.gov/data/2020/dec/pl?get=NAME&for=state:* (None of the territories in there). 

I think best bet here is to warn the user before take-off that they need to filter them out. Fixed in hwru branch. Now warns: 

```
The wru package does not support US territories, please filter them out of your voter.file data
```
