### ISSUE TITLE
probability estimates conditional on other rows in dataset

### ISSUE THREAD

**Issue by bthowe** [kosukeimai/wru#68]
These all yield different estimates for the same surname, which is contrary to my expectation.

library(wru)
future.callr::callr
surname <- c("SULLIVAN")
predict_race(voter.file=data.frame(surname), surname.only=TRUE)

surname <- c("SULLIVAN", "SULLIVAN")
predict_race(voter.file=data.frame(surname), surname.only=TRUE)

surname <- c("SULLIVAN", "SULLIVAN", "SULLIVAN")
predict_race(voter.file=data.frame(surname), surname.only=TRUE)

**Comment by 1beb** [comment]
@solivella will need to look at this more

BISG isn't designed to take a very small sample of the voterfile for surname.only = TRUE because it tries to use a fixed race marginal to distribute predictions. If you have an exceedingly small voter file sample, you may want to feed them individually (row by row) to `predict_race`. 

In your code, for surname only with no census data you don't need to specify a parallel plan. The correct form would be something like: 


```
library(wru)
library(future)
plan(future.callr::callr)
...
```


Note @solivella we should probably add a warning when we see a small voter.file sample or a race-biased sample of last names with surname only.

**Comment by kkprinceton** [comment]
FWIW I tried this code and couldn't replicate the problem

**Comment by 1beb** [comment]
@bthowe This has been fixed in the most recent release available on github. It will be a bit before this gets pushed to CRAN, so you can install the development version from github using the remotes package:  

```
remotes::install_github("kosukeimai/wru")
```
